export const productData = [
  {
    id: 1,
    title: "Single Room",
    price: "20 for one night",
    description: "A cozy Single Room, perfect for solo travelers looking for comfort and convenience. It includes a comfortable twin bed, free Wi-Fi, a work desk, and a private bathroom. Ideal for business trips or short stays.",
    category: "Rooms",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFHE6gL7IE3GSUl3F_Gdd5uE4MNiH-XYC_WQ&s",
    rating: { rate: 3.9 },
  },
  {
    id: 2,
    title: "Single Room",
    price: "20 for one night",
    description: "Our Single Room offers privacy and relaxation for the solo traveler. Features include a twin bed, complimentary toiletries, air conditioning, and a flat-screen TV. Room service is available.",
    category: "Rooms",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLTv6_RPzgKOWOtqDEO5STXz-WMfJ4pJ8rLg&s",
    rating: { rate: 3.9 },
  },
  {
    id: 3,
    title: "Double Room",
    price: "40 for one night",
    description: "The Double Room is designed for couples or friends, featuring a double bed, en-suite bathroom, and modern amenities like Wi-Fi and satellite TV. Enjoy complimentary breakfast and access to the hotel's fitness center.",
    category: "Rooms",
    image: "https://res.cloudinary.com/traveltripperweb/image/upload/c_limit,f_auto,h_2500,q_auto,w_2500/v1580455406/vahre6fc9gt8ygcdmkuu.jpg",
    rating: { rate: 4.1, count: 259 },
  },
  {
    id: 4,
    title: "Double Room",
    price: "40 for one night",
    description: "Spacious Double Room with a queen-sized bed, perfect for a relaxing stay. Includes a mini-fridge, safe, and 24-hour room service. Guests can enjoy complimentary parking and access to the spa.",
    category: "Rooms",
    image: "https://djmzubtjl6upi.cloudfront.net/wp-content/uploads/sites/3/2017/12/Deluxe-Double-Guestroom2.jpg",
    rating: { rate: 4.1, count: 259 },
  },
  {
    id: 5,
    title: "Triple Room",
    price: "50 for one night",
    description: "Ideal for families or small groups, the Triple Room features three twin beds, a spacious seating area, and a balcony with city views. Additional amenities include a mini-bar, tea/coffee maker, and daily housekeeping.",
    category: "Rooms",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2EKSxKTvEMVq2c_lDtZR-P1yrEhbQGBL1dA&s",
    rating: { rate: 4.7, count: 500 },
  },
  {
    id: 6,
    title: "Triple Room",
    price: "50 for one night",
    description: "The Triple Room offers comfort for three guests, with modern furnishings, premium bedding, and a private balcony. Enjoy a complimentary breakfast buffet and access to the rooftop pool.",
    category: "Rooms",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfSDJACJlK4s1esa7x4XwV9vZpH4EVYw2Oiw&s",
    rating: { rate: 4.7, count: 500 },
  },
  {
    id: 7,
    title: "Standard Room",
    price: "15 for one night",
    description: "Our budget-friendly Standard Room offers great value without sacrificing comfort. It includes a double bed, free Wi-Fi, a flat-screen TV, and complimentary toiletries. Perfect for budget-conscious travelers.",
    category: "Rooms",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKTedETTc9bCKCnAZlkrPqblODiYZcnm4NhQ&s",
    rating: { rate: 2.1, count: 430 },
  },
  {
    id: 8,
    title: "Standard Room",
    price: "15 for one night",
    description: "The Standard Room offers simplicity and comfort, featuring a queen-sized bed, air conditioning, and a private bathroom with a shower. Guests can enjoy in-room dining and access to the lounge area.",
    category: "Rooms",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpGkLhzzfIpI7Drs013uwiKUhINv_J9uVbUw&s",
    rating: { rate: 2.1, count: 430 },
  },
  {
    id: 9,
    title: "Deluxe Room",
    price: "60 for one night",
    description: "Our Deluxe Room is an upscale option with a king-sized bed, luxurious linens, and a spacious bathroom. Enjoy complimentary snacks, a minibar, and access to the VIP lounge.",
    category: "Rooms",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTj_uw4zliyzqHzQlLTrMhJSCr1tIU9Vvj59A&s",
    rating: { rate: 4.6, count: 400 },
  },
  {
    id: 10,
    title: "Deluxe Room",
    price: "60 for one night",
    description: "The Deluxe Room offers superior comfort and elegance, with stunning views, a plush king-sized bed, and high-end toiletries. Perfect for business travelers or those seeking a luxurious stay.",
    category: "Rooms",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSa0fEBxY_USZf0XJBWODuQwQvAv9k2VngLOA&s",
    rating: { rate: 4.6, count: 400 },
  },
  {
    id: 11,
    title: "Presidential Suites",
    price: "80 for one night",
    description: "The Presidential Suite offers the ultimate luxury experience, featuring a grand living space, private dining area, and personal concierge service. Includes exclusive access to the executive lounge and a private spa.",
    category: "suites",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfGnEwMpJnpzfN2Ovxj4AVp1l6CxB7sck1-Q&s",
    rating: { rate: 3.9, count: 70 },
  },
  {
    id: 12,
    title: "Presidential Suites",
    price: "80 for one night",
    description: "A lavish Presidential Suite with stunning views, featuring multiple rooms, a grand master bedroom, a private jacuzzi, and butler service. Ideal for guests seeking an opulent stay.",
    category: "suites",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQuk3jl_qgz0og_Sn5FRI84J7T0huLkq-9eA&s",
    rating: { rate: 3.9, count: 70 },
  },
  {
    id: 13,
    title: "Penthouse Suite",
    price: "100 for one night",
    description: "The Penthouse Suite is an exclusive luxury accommodation located on the top floor, offering panoramic views, a private terrace, and premium services such as a dedicated concierge and access to a private pool.",
    category: "suites",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyw538cSI4S9kWFwfsrEHIE24873S7La-Btw&s",
    rating: { rate: 3, count: 400 },
  },
  {
    id: 14,
    title: "Penthouse Suite",
    price: "100 for one night",
    description: "A luxurious Penthouse Suite located on the top floor with exclusive amenities such as a private bar, a home theater, a jacuzzi, and floor-to-ceiling windows. Perfect for those seeking an unforgettable experience.",
    category: "suites",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5GvbgXRvbVkoMKYc29UsbITfg1gz5OW-XhA&s",
    rating: { rate: 3, count: 400 },
  },
 
];
